//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppSalesManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MaterialGood
    {
        public MaterialGood()
        {
            this.RSInwardDetails = new HashSet<RSInwardDetail>();
            this.SaleDetails = new HashSet<SaleDetail>();
        }
    
        public long ID { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<RSInwardDetail> RSInwardDetails { get; set; }
        public virtual ICollection<SaleDetail> SaleDetails { get; set; }
    }
}
