//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppSalesManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RSInward
    {
        public RSInward()
        {
            this.RSInwardDetails = new HashSet<RSInwardDetail>();
        }
    
        public long ID { get; set; }
        public string RSInwardNo { get; set; }
        public string Seller { get; set; }
        public Nullable<System.DateTime> RSInwardDate { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
        public Nullable<decimal> TotalVAT { get; set; }
        public Nullable<decimal> TotalDiscount { get; set; }
    
        public virtual ICollection<RSInwardDetail> RSInwardDetails { get; set; }
    }
}
