//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppSalesManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RSInwardDetail
    {
        public long ID { get; set; }
        public Nullable<long> RSInwardID { get; set; }
        public Nullable<long> MaterialGoodsID { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<decimal> VATAmount { get; set; }
        public Nullable<decimal> DiscountAmount { get; set; }
        public Nullable<long> Order { get; set; }
    
        public virtual MaterialGood MaterialGood { get; set; }
        public virtual RSInward RSInward { get; set; }
    }
}
