//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppSalesManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserView
    {
        public long ID { get; set; }
        public string NameLogin { get; set; }
        public string Password { get; set; }
        public string Email { get; set; }
        public string Address { get; set; }
        public string ROLENAME { get; set; }
    }
}
